# ------------------------------------------------------------------------------
#
# Shell sourcing file order :
#	zshenv -> zprofile -> zshrc -> zlogin
#
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# Theme

# Instant prompt (has to be at the very top of zshrc)
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
	source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# include .zshrc_themes if it exists
[ -f $HOME/.config/zsh/zshrc_themes ] && . $HOME/.config/zsh/zshrc_themes

# ------------------------------------------------------------------------------
# Settings

eval "$(rbenv init -)" # init ruby environment

eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" # Homebrew

zstyle ':omz:update' mode reminder

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
	export EDITOR='vim'
else
	export EDITOR='nvim'
fi

DISABLE_UNTRACKED_FILES_DIRTY="true"

# INCLUDE : .zshrc_plugins if it exists
[ -f $HOME/.config/zsh/zshrc_plugins ] && . $HOME/.config/zsh/zshrc_plugins

# INCLUDE : .oh-my-zsh if it exists
[ -f $ZSH/oh-my-zsh.sh ] && . $ZSH/oh-my-zsh.sh

# ------------------------------------------------------------------------------
# Aliases

# INCLUDE : .zshrc_aliases if it exists
[ -f $HOME/.config/zsh/zshrc_aliases ] && . $HOME/.config/zsh/zshrc_aliases

bindkey -v # Set VIM commands mode

bindkey '^R' history-incremental-search-backward # Recursive search

# ------------------------------------------------------------------------------

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
