#!/bin/bash

COLOR_BLACK=$(tput setaf 0)
COLOR_RED=$(tput setaf 1)
COLOR_GREEN=$(tput setaf 2)
COLOR_YELLOW=$(tput setaf 3)
COLOR_LIME_YELLOW=$(tput setaf 190)
COLOR_POWDER_BLUE=$(tput setaf 153)
COLOR_BLUE=$(tput setaf 4)
COLOR_MAGENTA=$(tput setaf 5)
COLOR_CYAN=$(tput setaf 6)
COLOR_WHITE=$(tput setaf 7)
COLOR_BRIGHT=$(tput bold)
COLOR_NORMAL=$(tput sgr0)
COLOR_BLINK=$(tput blink)
COLOR_REVERSE=$(tput smso)
COLOR_UNDERLINE=$(tput smul)
