# Default colors
[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
startup_mode = "SimpleFullscreen"

[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]
live_config_reload = true
